[project]
name = "zipnerf"
version = "0.1.0"

dependencies=[
    "nerfstudio"
]

[tool.setuptools.packages.find]
include = ["zipnerf*"]

[project.entry-points.'nerfstudio.method_configs']
zipnerf = 'zipnerf.zipnerf_config:zipnerf_method'
